
CREATE SEQUENCE tipo_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;
  
CREATE SEQUENCE subtipo_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE usuario_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE solicitud_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE auditoria_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE encuesta_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE observacion_seq
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCACHE;