package anai.edu.ec.mesaayuda.Entity;
// Generated 09/05/2020 17:29:59 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="DEPARTAMENTO"
    ,schema="MA01"
)
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String nombreDepartamento;
     private Integer estadoBorrado;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Departamento() {
    }

	
    public Departamento(Integer idDepartamento, String nombreDepartamento) {
        this.idDepartamento = idDepartamento;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(Integer idDepartamento, String nombreDepartamento, Integer estadoBorrado, Set<Usuario> usuarios) {
       this.idDepartamento = idDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.estadoBorrado = estadoBorrado;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="ID_DEPARTAMENTO", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    
    @Column(name="NOMBRE_DEPARTAMENTO", nullable=false, length=100)
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }

    
    @Column(name="ESTADO_BORRADO", precision=22, scale=0)
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
}


