package anai.edu.ec.mesaayuda.Entity;
// Generated 25/04/2020 18:45:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Encuesta generated by hbm2java
 */
@Entity
@Table(name="ENCUESTA"
    ,schema="MA01"
)
public class Encuesta  implements java.io.Serializable {


     private Integer idEncuesta;
     private String nombre;
     private String descripcion;
     private String codigoEmbebido;
     private String codigoRegistro;
     private Integer estadoBorrado;
     private Set<SolicitudAyuda> solicitudAyudas = new HashSet<SolicitudAyuda>(0);

    public Encuesta() {
    }

	
    public Encuesta(Integer idEncuesta, String nombre, String descripcion, String codigoEmbebido, String codigoRegistro) {
        this.idEncuesta = idEncuesta;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.codigoEmbebido = codigoEmbebido;
        this.codigoRegistro = codigoRegistro;
    }
    public Encuesta(Integer idEncuesta, String nombre, String descripcion, String codigoEmbebido, String codigoRegistro, Integer estadoBorrado, Set<SolicitudAyuda> solicitudAyudas) {
       this.idEncuesta = idEncuesta;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.codigoEmbebido = codigoEmbebido;
       this.codigoRegistro = codigoRegistro;
       this.estadoBorrado = estadoBorrado;
       this.solicitudAyudas = solicitudAyudas;
    }
   
     @Id 

    
    @Column(name="ID_ENCUESTA", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdEncuesta() {
        return this.idEncuesta;
    }
    
    public void setIdEncuesta(Integer idEncuesta) {
        this.idEncuesta = idEncuesta;
    }

    
    @Column(name="NOMBRE", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="DESCRIPCION", nullable=false, length=1000)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="CODIGO_EMBEBIDO", nullable=false, length=1000)
    public String getCodigoEmbebido() {
        return this.codigoEmbebido;
    }
    
    public void setCodigoEmbebido(String codigoEmbebido) {
        this.codigoEmbebido = codigoEmbebido;
    }

    
    @Column(name="CODIGO_REGISTRO", nullable=false, length=25)
    public String getCodigoRegistro() {
        return this.codigoRegistro;
    }
    
    public void setCodigoRegistro(String codigoRegistro) {
        this.codigoRegistro = codigoRegistro;
    }

    
    @Column(name="ESTADO_BORRADO", precision=22, scale=0)
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="encuesta")
    public Set<SolicitudAyuda> getSolicitudAyudas() {
        return this.solicitudAyudas;
    }
    
    public void setSolicitudAyudas(Set<SolicitudAyuda> solicitudAyudas) {
        this.solicitudAyudas = solicitudAyudas;
    }




}


