package anai.edu.ec.mesaayuda.Entity;
// Generated 05/05/2020 16:37:45 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Observacion generated by hbm2java
 */
@Entity
@Table(name="OBSERVACION"
    ,schema="MA01"
)
public class Observacion  implements java.io.Serializable {


     private Integer idObservacion;
     private Usuario usuario;
     private SolicitudAyuda solicitudAyuda;
     private String mensaje;
     private Date fechaMensaje;

    public Observacion() {
    }

	
    public Observacion(Integer idObservacion, Usuario usuario, SolicitudAyuda solicitudAyuda, String mensaje) {
        this.idObservacion = idObservacion;
        this.usuario = usuario;
        this.solicitudAyuda = solicitudAyuda;
        this.mensaje = mensaje;
    }
    public Observacion(Integer idObservacion, Usuario usuario, SolicitudAyuda solicitudAyuda, String mensaje, Date fechaMensaje) {
       this.idObservacion = idObservacion;
       this.usuario = usuario;
       this.solicitudAyuda = solicitudAyuda;
       this.mensaje = mensaje;
       this.fechaMensaje = fechaMensaje;
    }
   
     @Id 

    
    @Column(name="ID_OBSERVACION", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdObservacion() {
        return this.idObservacion;
    }
    
    public void setIdObservacion(Integer idObservacion) {
        this.idObservacion = idObservacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_USUARIO", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_SOLICITUD", referencedColumnName="ID_SOLICITUD", nullable=false), 
        @JoinColumn(name="ID_GRUPO", referencedColumnName="ID_GRUPO", nullable=false) } )
    public SolicitudAyuda getSolicitudAyuda() {
        return this.solicitudAyuda;
    }
    
    public void setSolicitudAyuda(SolicitudAyuda solicitudAyuda) {
        this.solicitudAyuda = solicitudAyuda;
    }

    
    @Column(name="MENSAJE", nullable=false, length=200)
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA_MENSAJE", length=7)
    public Date getFechaMensaje() {
        return this.fechaMensaje;
    }
    
    public void setFechaMensaje(Date fechaMensaje) {
        this.fechaMensaje = fechaMensaje;
    }

}


