package anai.edu.ec.mesaayuda.Entity;
// Generated 19/03/2020 10:04:58 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SolicitudAyudaId generated by hbm2java
 */
@Embeddable
public class SolicitudAyudaId  implements java.io.Serializable {


     private Integer idSolicitud;
     private String idGrupo;

    public SolicitudAyudaId() {
    }

    public SolicitudAyudaId(Integer idSolicitud, String idGrupo) {
       this.idSolicitud = idSolicitud;
       this.idGrupo = idGrupo;
    }
   


    @Column(name="ID_SOLICITUD", nullable=false, precision=22, scale=0)
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }


    @Column(name="ID_GRUPO", nullable=false, length=5)
    public String getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(String idGrupo) {
        this.idGrupo = idGrupo;
    }

/*
   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SolicitudAyudaId) ) return false;
		 SolicitudAyudaId castOther = ( SolicitudAyudaId ) other; 
         
		 return ( (this.getIdSolicitud()==castOther.getIdSolicitud()) || ( this.getIdSolicitud()!=null && castOther.getIdSolicitud()!=null && this.getIdSolicitud().equals(castOther.getIdSolicitud()) ) )
 && ( (this.getIdGrupo()==castOther.getIdGrupo()) || ( this.getIdGrupo()!=null && castOther.getIdGrupo()!=null && this.getIdGrupo().equals(castOther.getIdGrupo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdSolicitud() == null ? 0 : this.getIdSolicitud().hashCode() );
         result = 37 * result + ( getIdGrupo() == null ? 0 : this.getIdGrupo().hashCode() );
         return result;
   }   
*/

}


