package anai.edu.ec.mesaayuda.Entity;
// Generated 19/03/2020 10:04:58 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoGrupo generated by hbm2java
 */
@Entity
@Table(name="TIPO_GRUPO"
    ,schema="MA01"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOMBRE_TIPO") 
)
public class TipoGrupo  implements java.io.Serializable {


     private Integer idTipo;
     private Grupo grupo;
     private String nombreTipo;
     private Integer estadoBorrado;
     private Set<SolicitudAyuda> solicitudAyudas = new HashSet<SolicitudAyuda>(0);
     private Set<Subtipo> subtipos = new HashSet<Subtipo>(0);
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public TipoGrupo() {
    }

	
    public TipoGrupo(Integer idTipo, Grupo grupo, String nombreTipo) {
        this.idTipo = idTipo;
        this.grupo = grupo;
        this.nombreTipo = nombreTipo;
    }
    public TipoGrupo(Integer idTipo, Grupo grupo, String nombreTipo, Integer estadoBorrado, Set<SolicitudAyuda> solicitudAyudas, Set<Subtipo> subtipos, Set<Usuario> usuarios) {
       this.idTipo = idTipo;
       this.grupo = grupo;
       this.nombreTipo = nombreTipo;
       this.estadoBorrado = estadoBorrado;
       this.solicitudAyudas = solicitudAyudas;
       this.subtipos = subtipos;
       this.usuarios = usuarios;
    }
   
     @Id 

    
    @Column(name="ID_TIPO", unique=true, nullable=false, precision=22, scale=0)
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_GRUPO", nullable=false)
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

    
    @Column(name="NOMBRE_TIPO", unique=true, nullable=false, length=50)
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }

    
    @Column(name="ESTADO_BORRADO", precision=22, scale=0)
    public Integer getEstadoBorrado() {
        return this.estadoBorrado;
    }
    
    public void setEstadoBorrado(Integer estadoBorrado) {
        this.estadoBorrado = estadoBorrado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoGrupo")
    public Set<SolicitudAyuda> getSolicitudAyudas() {
        return this.solicitudAyudas;
    }
    
    public void setSolicitudAyudas(Set<SolicitudAyuda> solicitudAyudas) {
        this.solicitudAyudas = solicitudAyudas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoGrupo")
    public Set<Subtipo> getSubtipos() {
        return this.subtipos;
    }
    
    public void setSubtipos(Set<Subtipo> subtipos) {
        this.subtipos = subtipos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoGrupo")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }

    @Override
    public String toString() {
        return "TipoGrupo{" + "idTipo=" + idTipo + ", grupo=" + grupo.toString() + ", nombreTipo=" + nombreTipo + ", estadoBorrado=" + estadoBorrado;
    }
    
    
}


